# ============================================================
# ONLINE RETAIL II - DATA CLEANING & PREPROCESSING
# ============================================================
# Dataset: UK-based Online Retail (Non-Store)
# Period: January 1, 2010 - November 30, 2011
# Original Records: 1,067,371
# Clean Records: 729,751
# ============================================================

In [1]:
!pip install kaggle

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaggle in .\AppData\Roaming\Python\Python314\site-packages (2.1.2)
Requirement already satisfied: bleach in .\AppData\Roaming\Python\Python314\site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in .\AppData\Roaming\Python\Python314\site-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.23 in .\AppData\Roaming\Python\Python314\site-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in .\AppData\Roaming\Python\Python314\site-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in .\AppData\Roaming\Python\Python314\site-packages (from kaggle) (7.35.0)
Requirement already satisfied: python-dateutil in .\AppData\Roaming\Python\Python314\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in .\AppData\Roaming\Python\Python314\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in .\AppData\Roaming\Python\Python314\site-packages (from kaggle) (2.34.2)
Requirement already satisfied: tqdm in .\AppData\Roaming\Python\Python314\site-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in .\AppData\Roaming\Python\Python314\site-packages (from kaggle) (2.7.0)
Requirement already satisfied: webencodings in .\AppData\Roaming\Python\Python314\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in .\AppData\Roaming\Python\Python314\site-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in .\AppData\Roaming\Python\Python314\site-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in .\AppData\Roaming\Python\Python314\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in .\AppData\Roaming\Python\Python314\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in .\AppData\Roaming\Python\Python314\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in .\AppData\Roaming\Python\Python314\site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in .\AppData\Roaming\Python\Python314\site-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in .\AppData\Roaming\Python\Python314\site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in .\AppData\Roaming\Python\Python314\site-packages (from nbformat->jupytext->kaggle) (5.15.0)
Requirement already satisfied: attrs>=22.2.0 in .\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in .\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in .\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in .\AppData\Roaming\Python\Python314\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in .\AppData\Roaming\Python\Python314\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.9.6)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python314\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in .\AppData\Roaming\Python\Python314\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in .\AppData\Roaming\Python\Python314\site-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\AppData\Roaming\Python\Python314\site-packages (from requests->kaggle) (3.16)
Requirement already satisfied: certifi>=2023.5.7 in .\AppData\Roaming\Python\Python314\site-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: colorama in .\AppData\Roaming\Python\Python314\site-packages (from tqdm->kaggle) (0.4.6)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!kaggle datasets list

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.0), please consider upgrading to the latest version (2.0.2)
ref                                                                     title                                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating
----------------------------------------------------------------------  --------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
laveshjadon/ai-impact-on-students                                       Impact of Ai on Students                               1187170  2026-05-10 23:12:10.070000           6218        158                1
muhammadwaqas023/ai-impact-in-future-on-jobs-market-in-2030             Ai Impact in future on jobs market in 2030              108338  2026-05-24 15:12:54.047000           1842         44                1
divyjain28/superstore-sales                                             Superstore Sales Analysis                              1579499  2026-05-15 08:16:38.500000           1293         31                1
meruvakodandasuraj/video-game-sales-and-metacritic-intelligence-198026  Video Game Sales & Metacritic Intelligence 1980–26     2477396  2026-05-28 05:04:49.980000            954         31                1
shambhurajejagadale/student-performance-prediction-dataset              Student Performance Prediction Dataset                   84282  2026-05-09 15:49:58.877000           3902         91                1
algozee/teenager-menthal-healy                                          Social Media Impact on Teen Mental Health                16190  2026-04-05 08:04:21.823000          37487        768                1
zynicide/wine-reviews                                                   Wine Reviews                                          53336293  2017-11-27 17:08:04.700000         354334       3872        0.7941176
hideyukizushi/sgkfk-202604041716                                        SGKF|K-202604041716                                   23651366  2026-04-04 10:36:36.847000            338          4        0.5882353
nolanbconaway/pitchfork-data                                            18,393 Pitchfork Reviews                              34891456  2017-01-13 04:18:10.113000          18001        459        0.7058824
rishikeshjani/perch-onnx-for-birdclef-2026                              Perch-onnx-for-birdclef+2026                         395240323  2026-03-30 07:07:25.863000           1979         20       0.47058824
datasnaek/youtube-new                                                   Trending YouTube Video Statistics                    210575746  2019-06-03 00:56:47.177000         305835       5931        0.7941176
jpmiller/publicassistance                                               US Public Food Assistance 1 - WIC                       304041  2023-04-17 20:01:05.960000          26408        511        0.9411765
nasa/kepler-exoplanet-search-results                                    Kepler Exoplanet Search Results                        1215549  2017-10-10 18:26:59.497000          23027        861        0.8235294
rtatman/188-million-us-wildfires                                        1.88 Million US Wildfires                            176270559  2020-05-12 21:03:49.213000          44416       1434        0.8235294
residentmario/things-on-reddit                                          Things on Reddit                                      16773230  2017-10-26 14:10:15.157000          16220        322        0.5882353
dansbecker/powerlifting-database                                        powerlifting-database                                  9277600  2019-04-30 21:07:41.560000          27103        396        0.5882353
jaejohn/perch-meta                                                      perch_meta                                             4583047  2026-03-13 12:07:38.517000           1223         14        0.1764706
datasnaek/chess                                                         Chess Game Dataset (Lichess)                           2903760  2017-09-04 03:09:09.453000          65372       1479        0.8235294
residentmario/ramen-ratings                                             Ramen Ratings                                            40762  2018-01-11 16:04:39.893000          56633        981        0.7058824
sanyamdhadiwal2302/netflix-data                                         Netflix Data                                           1783607  2026-05-22 18:10:36.380000           1735         41        0.9411765

In [3]:
!kaggle datasets download -d lakshmi25npathi/online-retail-dataset

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.0), please consider upgrading to the latest version (2.0.2)
Dataset URL: https://www.kaggle.com/datasets/lakshmi25npathi/online-retail-dataset
License(s): other
online-retail-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)

In [4]:
import os
import zipfile

zip_file_path = "online-retail-dataset.zip"
extraction_target = "data"

if os.path.exists(zip_file_path):
    try:
        with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
            zip_ref.extractall(extraction_target)
        print(f"Successfully extracted {zip_file_path} to the '{extraction_target}' folder.")
    except zipfile.BadZipFile:
        print(f"Error: The file '{zip_file_path}' is corrupted. Please re-download.")

else:
    print(f"Error: '{zip_file_path}' not found. Check your Kaggle download step.")

Successfully extracted online-retail-dataset.zip to the 'data' folder.

##Load into pandas

In [5]:
import pandas as pd

df = pd.read_excel("data/online_retail_II.xlsx")
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [6]:
xls = pd.ExcelFile("data/online_retail_II.xlsx")
print(xls.sheet_names)

['Year 2009-2010', 'Year 2010-2011']

Use Latest Year Sheet

In [7]:
df1 = pd.read_excel(
    "data/online_retail_II.xlsx",
    sheet_name='Year 2009-2010'
)
df2 = pd.read_excel(
    "data/online_retail_II.xlsx",
    sheet_name='Year 2010-2011'
)

df = pd.concat([df1,df2], ignore_index= True)

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

## Data Understanding

In [8]:
df.shape

(1067371, 8)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 65.1+ MB

In [10]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [11]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,1.067371e+06,1067371,1.067371e+06,824364.000000
mean,9.938898e+00,2011-01-02 21:13:55.394028544,4.649388e+00,15324.638504
min,-8.099500e+04,2009-12-01 07:45:00,-5.359436e+04,12346.000000
25%,1.000000e+00,2010-07-09 09:46:00,1.250000e+00,13975.000000
50%,3.000000e+00,2010-12-07 15:28:00,2.100000e+00,15255.000000
75%,1.000000e+01,2011-07-22 10:23:00,4.150000e+00,16797.000000
max,8.099500e+04,2011-12-09 12:50:00,3.897000e+04,18287.000000
std,1.727058e+02,NaN,1.235531e+02,1697.464450

## Standardize Column Names

In [12]:
df.columns = df.columns.str.strip().str.replace(' ','_')
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer_ID', 'Country'],
      dtype='object')

In [13]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer_ID', 'Country'],
      dtype='object')

In [14]:
df = df[
    (df['InvoiceDate'] >= '2010-01-01') &
    (df['InvoiceDate'] < '2011-12-01')
]

In [15]:
print(df.shape)
print(df['InvoiceDate'].min(), df['InvoiceDate'].max())

(996617, 8)
2010-01-04 09:24:00 2011-11-30 17:42:00

In [16]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4139
Quantity            0
InvoiceDate         0
Price               0
Customer_ID    221675
Country             0
dtype: int64

## Remove Missing Customer ID & Description Null

In [17]:
df = df.dropna(subset=['Customer_ID', 'Description'])

df['Customer_ID'] = df['Customer_ID'].astype('Int64')

In [18]:
## Validate Cancellations 
canceled_invoices = df['Invoice'].astype(str).str.startswith('C')
all_canceled_have_negative_qty = df[canceled_invoices]['Quantity'].max() <= 0
outliers = df[(df['Quantity'] < 0) & (~canceled_invoices)]

print(f"Are all cancellations caught by Quantity filter?: {all_canceled_have_negative_qty}")
print(f"Negative quantities missing 'C' prefix: {len(outliers)}")

Are all cancellations caught by Quantity filter?: True
Negative quantities missing 'C' prefix: 0

## Remove Invalid Transactions

In [19]:
# Remove negative or zero quantity & zero or negative price
df = df[(df['Quantity'] > 0) & (df['Price'] > 0)]

print(f"Shape after removing cancelled & invalid transactions: {df.shape}")
print(f"Total rows after cleaning: {df.shape[0]}")

Shape after removing cancelled & invalid transactions: (757490, 8)
Total rows after cleaning: 757490

##Fix data type

In [20]:
df['Customer_ID'] = df['Customer_ID'].astype(int)

## Create Revenue Column

In [21]:
df['TotalPrice'] = df['Quantity']*df['Price']

print("Quantity statistics:")
print(df['Quantity'].describe())
print("\nPrice statistics:")
print(df['Price'].describe())
print("\nTotalPrice statistics:")
print(df['TotalPrice'].describe())

Quantity statistics:
count    757490.000000
mean         13.226049
std         114.356417
min           1.000000
25%           2.000000
50%           5.000000
75%          12.000000
max       74215.000000
Name: Quantity, dtype: float64

Price statistics:
count    757490.000000
mean          3.217918
std          29.994080
min           0.001000
25%           1.250000
50%           1.950000
75%           3.750000
max       10953.500000
Name: Price, dtype: float64

TotalPrice statistics:
count    757490.000000
mean         21.833376
std         124.988569
min           0.001000
25%           4.950000
50%          11.900000
75%          19.500000
max       77183.600000
Name: TotalPrice, dtype: float64

## Final Validation

In [22]:
df.sort_values(by='TotalPrice', ascending=False).head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer_ID,Country,TotalPrice
587080,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346,United Kingdom,77183.60
748132,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,2011-06-10 15:28:00,649.50,15098,United Kingdom,38970.00
432176,530715,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,9360,2010-11-04 11:36:00,1.69,15838,United Kingdom,15818.40
135013,502263,M,Manual,1,2010-03-23 15:22:00,10953.50,12918,United Kingdom,10953.50
358639,524159,M,Manual,1,2010-09-27 16:12:00,10468.80,14063,United Kingdom,10468.80
74356,496115,M,Manual,1,2010-01-29 11:04:00,8985.60,17949,United Kingdom,8985.60
228042,511465,15044A,PINK PAPER PARASOL,3500,2010-06-08 12:59:00,2.55,18008,United Kingdom,8925.00
698843,551697,POST,POSTAGE,1,2011-05-03 13:46:00,8142.75,16029,United Kingdom,8142.75
873786,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,2011-09-20 11:05:00,5.06,17450,United Kingdom,7144.72
129903,501766,M,Manual,1,2010-03-19 11:35:00,6958.17,15760,Norway,6958.17

In [23]:
df[df['StockCode'].isin(['M','POST'])]['StockCode'].value_counts()

StockCode
POST    1748
M        690
Name: count, dtype: int64

In [24]:
# Removing the suspicious entries
df = df[~df['StockCode'].isin(['M','POST'])]

print(f"Shape after removing the data error: {df.shape}")
print(f"Rows removed: {757490 - df.shape[0]}")

Shape after removing the data error: (755052, 9)
Rows removed: 2438

In [25]:
df.duplicated().sum()

np.int64(25301)

In [26]:
df = df.drop_duplicates()

In [27]:
df.shape

(729751, 9)

In [28]:
# Check final dataset
print(df.info())
print("\n" + "="*50)
print("Data Quality Summary:")
print(f"Total Records: {df.shape[0]}")
print(f"Date Range: {df['InvoiceDate'].min()} to {df['InvoiceDate'].max()}")
print(f"Unique Customers: {df['Customer_ID'].nunique()}")
print(f"Unique Products: {df['StockCode'].nunique()}")
print(f"Countries: {df['Country'].nunique()}")
print(f"\nMissing Values:\n{df.isnull().sum()}")

<class 'pandas.core.frame.DataFrame'>
Index: 729751 entries, 45228 to 1041829
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      729751 non-null  object
 1   StockCode    729751 non-null  object
 2   Description  729751 non-null  object
 3   Quantity     729751 non-null  int64
 4   InvoiceDate  729751 non-null  datetime64[ns]
 5   Price        729751 non-null  float64
 6   Customer_ID  729751 non-null  int64
 7   Country      729751 non-null  object
 8   TotalPrice   729751 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 55.7+ MB
None

==================================================
Data Quality Summary:
Total Records: 729751
Date Range: 2010-01-04 09:24:00 to 2011-11-30 17:37:00
Unique Customers: 5746
Unique Products: 4507
Countries: 41

Missing Values:
Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer_ID    0
Country        0
TotalPrice     0
dtype: int64

## PUSH DATA TO SQL SERVER

In [29]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'SQL Server Native Client RDA 11.0', 'ODBC Driver 17 for SQL Server', 'ODBC Driver 18 for SQL Server', 'PostgreSQL ODBC Driver(ANSI)', 'PostgreSQL ODBC Driver(UNICODE)', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

## Create Connection

In [30]:
from sqlalchemy import create_engine
server = r"localhost\SQLEXPRESS"


engine = create_engine(
    f"mssql+pyodbc://@{server}/OnlineRetailDB?trusted_connection=yes&driver=ODBC+Driver+17+for+SQL+Server",
    fast_executemany=True
)

In [31]:
## Optimize Data Types

from sqlalchemy import  types

dtype_mapping = {
    'Invoice': types.String(20),
    'StockCode': types.String(20),
    'Description': types.String(255),
    'Quantity': types.Integer(),
    'InvoiceDate': types.DateTime(),
    'Price': types.Numeric(10,2),
    'Customer_ID': types.Integer(),
    'Country': types.String(50),
    'TotalPrice': types.Numeric(12,2)
}

In [32]:
## Push Data

df.to_sql(
    name="OnlineRetail",
    con=engine,
    if_exists='replace',
    index=False,
    dtype=dtype_mapping,
    chunksize=10000   # Important for performance
)

-73

## LOAD RAW DATA (FOR CANCELLATION ANALYSIS)

In [55]:
import pandas as pd
from sqlalchemy import create_engine

# ===== LOAD RAW DATA FROM EXCEL =====
print("Loading ORIGINAL raw data from Excel...")

df1 = pd.read_excel(
    "data/online_retail_II.xlsx",
    sheet_name='Year 2009-2010'
)
df2 = pd.read_excel(
    "data/online_retail_II.xlsx",
    sheet_name='Year 2010-2011'
)

# Combine both dataframes
df = pd.concat([df1, df2], ignore_index=True)
df.rename(columns={'Customer ID': 'Customer_ID'}, inplace=True)
if 'Total_Price' not in df.columns:
    df['TotalPrice'] = df['Quantity'] * df['Price']

print("Raw data loaded successfully!")
print(f"Total Rows: {len(df)}")
print(f"Cancelled orders: {(df['Quantity'] < 0).sum()}")
print(f"Missing CustomerID: {df['Customer_ID'].isna().sum()}")
print(f"Missing Description: {df['Description'].isna().sum()}")

dtype_mapping = {
    'Invoice': types.String(20),
    'StockCode': types.String(20),
    'Description': types.String(255),
    'Quantity': types.Integer(),
    'InvoiceDate': types.DateTime(),
    'Price': types.Numeric(10,2),
    'Customer_ID': types.Integer(),
    'Country': types.String(50),
    'TotalPrice': types.Numeric(12,2)
}

# ===== PUSH TO SQL SERVER =====
engine = create_engine(f"mssql+pyodbc://@{server}/OnlineRetailDB?trusted_connection=yes&driver=ODBC+Driver+17+for+SQL+Server",
    fast_executemany=True)

df.to_sql('OnlineRetailRaw', con=engine, if_exists='replace', index=False, dtype=dtype_mapping, chunksize=10000)

print("Data successfully pushed to SQL Server!")

Loading ORIGINAL raw data from Excel...
Raw data loaded successfully!
Total Rows: 1067371
Cancelled orders: 22950
Missing CustomerID: 243007
Missing Description: 4382
Data successfully pushed to SQL Server!