In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (2.0.0)
Requirement already satisfied: bleach in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (0.1.16)
Requirement already satisfied: packaging in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (24.2)
Requirement already satisfied: protobuf in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (7.34.1)
Requirement already satisfied: python-dateutil in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2.2.3)
Requirement already satisfied: webencodings in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil->kaggle) (1.16.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from requests->kaggle) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from requests->kaggle) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from requests->kaggle) (2024.8.30)
Requirement already satisfied: colorama in c:\users\rajee\appdata\local\programs\python\python313\lib\site-packages (from tqdm->kaggle) (0.4.6)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
!kaggle datasets list

ref                                                              title                                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating
---------------------------------------------------------------  --------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
nalisha/job-salary-prediction-dataset                            Job Salary Prediction Dataset                          3144815  2026-03-16 19:54:33.843000           5578        136                1
ssssws/chocolate-sales-dataset-2023-2024                         Chocolate Sales Dataset 2023 - 2024                   24420255  2026-03-07 04:58:02.387000           9257        145                1
grandmaster07/student-exam-performance-dataset-analysis          Student Exam Performance Dataset Analysis                96178  2026-02-10 09:47:13.350000          13633        234                1
mohankrishnathalla/sleep-health-and-daily-performance-dataset    Sleep Health & Daily Performance Dataset               4264617  2026-04-01 08:09:25.843000            783         24                1
b'zkskhurram/world-vs-asia-fuel-prices                             \xf0\x9f\x8c\x8d\xe2\x9b\xbd World vs Asia Fuel Prices                             23335  2026-03-30 10:48:07.263000            465         24                1  '
kienngx/nemotron-30b-competition-trainingdata-cot-labels         Nemotron-30B competition trainingdata (CoT+labels)     3903114  2026-03-24 01:42:23.850000            456         28                1
sharmajicoder/student-mental-health-and-burnout                  Student Mental Health and Burnout                    137596875  2026-03-18 19:03:34.140000           1978         45                1
alitaqishah/global-mental-health-crisis-index-2026               Global Mental Health Crisis Index 2026                    5553  2026-03-29 17:22:13.073000            293         34                1
ibrahimqasimi/global-commodity-prices-2000-2026                  Global Commodity Prices 2000-2026                       637018  2026-03-30 00:01:53.213000            260         26                1
darkmatternet/s-and-p-500-stocks-25-years-of-data-updated-daily  S&P 500 Stocks: 25 Years of Data (Updated Daily)     104153448  2026-04-01 02:21:48.450000            304         21                1
sehaj1104/indian-road-accident-dataset-20222025                  Indian Road Accident Dataset (2022–2025)                550714  2026-03-23 16:51:25.977000            612         22                1
ssssws/student-exam-performance-dataset                          Student Exam Performance Dataset                        322431  2026-03-12 07:12:09.130000            952         25                1
dhruvb2028/student-academic-performance-dataset-for-ml           Student Academic Performance Dataset for ML              27086  2026-03-20 14:13:48.107000           1289         39                1
obaidhere/amazon-bestsellers-price-vs-user-rating-analysis       Amazon Bestsellers: Price vs User Rating  Analysis       14857  2026-03-18 16:31:54.450000           1553         31                1
sohaibdevv/ai-and-data-science-job-market-2025-2026              AI & DS Job Market                                      188375  2026-03-19 15:07:10.143000           1108         26                1
b'bhushandivekar/video-game-sales-and-industry-data-1980-2024      \xf0\x9f\x8e\xae Video Game Sales & Industry Data (1980 - 2024)       2437021  2026-03-14 08:27:51.750000           2695         42                1  '
syedaeman2212/makeup-sales-in-2025                               Makeup sales in 2025                                     10082  2026-03-24 20:09:39.913000            661         42                1
alitaqishah/spotify-wrapped-2025-top-songs-and-artists           Spotify Wrapped 2025 | Top Songs & Artists                8564  2026-03-13 20:37:00.967000           2159         65                1
ibrahimqasimi/us-baby-names-1880-2024                            US Baby Names 1880-2024                                9395543  2026-03-26 15:31:28.730000            299         24                1
hassanjameelahmed/nike-nke-stock-market-analysis                 Nike (NKE) Stock Market Analysis                        182199  2026-03-23 12:00:39.147000            602         28                1

In [ ]:
!kaggle datasets download -d lakshmi25npathi/online-retail-dataset

Dataset URL: https://www.kaggle.com/datasets/lakshmi25npathi/online-retail-dataset
License(s): other
Downloading online-retail-dataset.zip to C:\Users\rajee

  0%|          | 0.00/43.3M [00:00<?, ?B/s]
  2%|2         | 1.00M/43.3M [00:01<01:00, 733kB/s]
  5%|4         | 2.00M/43.3M [00:01<00:30, 1.44MB/s]
  7%|6         | 3.00M/43.3M [00:01<00:19, 2.13MB/s]
  9%|9         | 4.00M/43.3M [00:02<00:15, 2.60MB/s]
 12%|#1        | 5.00M/43.3M [00:02<00:13, 2.96MB/s]
 14%|#3        | 6.00M/43.3M [00:02<00:12, 3.23MB/s]
 16%|#6        | 7.00M/43.3M [00:02<00:11, 3.43MB/s]
 18%|#8        | 8.00M/43.3M [00:03<00:10, 3.57MB/s]
 21%|##        | 9.00M/43.3M [00:03<00:09, 3.68MB/s]
 23%|##3       | 10.0M/43.3M [00:03<00:09, 3.75MB/s]
 25%|##5       | 11.0M/43.3M [00:04<00:08, 3.81MB/s]
 28%|##7       | 12.0M/43.3M [00:04<00:08, 3.85MB/s]
 30%|###       | 13.0M/43.3M [00:04<00:08, 3.88MB/s]
 32%|###2      | 14.0M/43.3M [00:04<00:07, 3.89MB/s]
 35%|###4      | 15.0M/43.3M [00:05<00:07, 3.89MB/s]
 37%|###6      | 16.0M/43.3M [00:05<00:07, 3.91MB/s]
 39%|###9      | 17.0M/43.3M [00:05<00:07, 3.92MB/s]
 42%|####1     | 18.0M/43.3M [00:05<00:06, 3.92MB/s]
 44%|####3     | 19.0M/43.3M [00:06<00:07, 3.47MB/s]
 46%|####6     | 20.0M/43.3M [00:06<00:06, 3.68MB/s]
 48%|####8     | 21.0M/43.3M [00:06<00:06, 3.84MB/s]
 51%|#####     | 22.0M/43.3M [00:06<00:05, 4.06MB/s]
 53%|#####3    | 23.0M/43.3M [00:07<00:06, 3.19MB/s]
 55%|#####5    | 24.0M/43.3M [00:07<00:06, 3.20MB/s]
 58%|#####7    | 25.0M/43.3M [00:08<00:07, 2.62MB/s]
 60%|######    | 26.0M/43.3M [00:08<00:06, 2.65MB/s]
 62%|######2   | 27.0M/43.3M [00:09<00:06, 2.56MB/s]
 65%|######4   | 28.0M/43.3M [00:09<00:06, 2.50MB/s]
 67%|######6   | 29.0M/43.3M [00:10<00:06, 2.45MB/s]
 69%|######9   | 30.0M/43.3M [00:10<00:05, 2.44MB/s]
 72%|#######1  | 31.0M/43.3M [00:10<00:04, 2.75MB/s]
 74%|#######3  | 32.0M/43.3M [00:11<00:03, 3.03MB/s]
 76%|#######6  | 33.0M/43.3M [00:11<00:03, 3.25MB/s]
 79%|#######8  | 34.0M/43.3M [00:11<00:02, 3.43MB/s]
 81%|########  | 35.0M/43.3M [00:11<00:02, 3.57MB/s]
 83%|########3 | 36.0M/43.3M [00:12<00:02, 3.29MB/s]
 85%|########5 | 37.0M/43.3M [00:12<00:01, 3.52MB/s]
 88%|########7 | 38.0M/43.3M [00:12<00:01, 3.69MB/s]
 90%|######### | 39.0M/43.3M [00:12<00:01, 4.03MB/s]
 92%|#########2| 40.0M/43.3M [00:13<00:00, 4.01MB/s]
 95%|#########4| 41.0M/43.3M [00:13<00:00, 3.98MB/s]
 97%|#########6| 42.0M/43.3M [00:13<00:00, 3.97MB/s]
 99%|#########9| 43.0M/43.3M [00:13<00:00, 3.95MB/s]
100%|##########| 43.3M/43.3M [00:14<00:00, 3.23MB/s]

In [ ]:
import zipfile

with zipfile.ZipFile("online-retail-dataset.zip",'r') as zip_ref:
    zip_ref.extractall("data")

##Load into pandas

In [ ]:
import pandas as pd

df = pd.read_excel("data/online_retail_II.xlsx")
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [ ]:
xls = pd.ExcelFile("data/online_retail_II.xlsx")
print(xls.sheet_names)

['Year 2009-2010', 'Year 2010-2011']

Use Latest Year Sheet

In [ ]:

df = pd.read_excel("data/online_retail_II.xlsx", sheet_name='Year 2010-2011')
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

## Data Understanding

In [ ]:
df.shape

(541910, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  object
 1   StockCode    541910 non-null  object
 2   Description  540456 non-null  object
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  datetime64[ns]
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [ ]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
Price               0
Customer ID    135080
Country             0
dtype: int64

In [ ]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,541910.000000,541910,541910.000000,406830.000000
mean,9.552234,2011-07-04 13:35:22.342307584,4.611138,15287.684160
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.080957,NaN,96.759765,1713.603074

## Standardize Column Names

In [ ]:
df.columns = df.columns.str.strip().str.replace(' ','_')
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer_ID', 'Country'],
      dtype='object')

## Remove missing customer ID

In [ ]:
df = df.dropna(subset=['Customer_ID'])

## Remove Invalid Transactions

In [ ]:
# Remove negative or zero quantity
df = df[df['Quantity']>0]

# Remove zero or negative price
df = df[df['Price']>0]

##Fix data type

In [ ]:
df['Customer_ID'] = df['Customer_ID'].astype(int)

## Create Revenue Column

In [ ]:
df['TotalPrice'] = df['Quantity']*df['Price']

## Handle Description Nulls

In [ ]:
df = df.dropna(subset=['Description'])

## Final Validation

In [ ]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 397885 entries, 0 to 541909
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      397885 non-null  object
 1   StockCode    397885 non-null  object
 2   Description  397885 non-null  object
 3   Quantity     397885 non-null  int64
 4   InvoiceDate  397885 non-null  datetime64[ns]
 5   Price        397885 non-null  float64
 6   Customer_ID  397885 non-null  int64
 7   Country      397885 non-null  object
 8   TotalPrice   397885 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 30.4+ MB

,Quantity,InvoiceDate,Price,Customer_ID,TotalPrice
count,397885.000000,397885,397885.000000,397885.000000,397885.000000
mean,12.988208,2011-07-10 23:41:56.419316992,3.116525,15294.416882,22.396989
min,1.000000,2010-12-01 08:26:00,0.001000,12346.000000,0.001000
25%,2.000000,2011-04-07 11:12:00,1.250000,13969.000000,4.680000
50%,6.000000,2011-07-31 14:39:00,1.950000,15159.000000,11.800000
75%,12.000000,2011-10-20 14:33:00,3.750000,16795.000000,19.800000
max,80995.000000,2011-12-09 12:50:00,8142.750000,18287.000000,168469.600000
std,179.331551,NaN,22.097861,1713.144421,309.070653

In [ ]:
df.shape

(397885, 9)

##PHASE 5- PUSH DATA TO SQL SERVER

In [ ]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'SQL Server Native Client RDA 11.0', 'ODBC Driver 17 for SQL Server', 'ODBC Driver 18 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

## Create Connection

In [ ]:
from sqlalchemy import create_engine
server = r"localhost\SQLEXPRESS"


engine = create_engine(
    f"mssql+pyodbc://@{server}/OnlineRetailDB?trusted_connection=yes&driver=ODBC+Driver+17+for+SQL+Server"
)

In [ ]:
## Optimize Data Types

from sqlalchemy import  types

dtype_mapping = {
    'Invoice': types.String(20),
    'Stockcode': types.String(20),
    'Description': types.String(255),
    'Quantity': types.Integer(),
    'InvoiceDate': types.DateTime(),
    'Price': types.Numeric(10,2),
    'Customer_ID': types.Integer(),
    'Country': types.String(50),
    'TotalPrice': types.Numeric(12,2)
}

In [ ]:
## Push Data

df.to_sql(
    name="OnlineRetail",
    con=engine,
    if_exists='replace',
    index=False,
    dtype=dtype_mapping,
    chunksize=10000   # Important for performance
)

8542